name: Nodejs Build Template
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        description: 'The Nodejs version to use for build'
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Nodejs ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: install dependencies
        run: npm install
